name: Daily Data Update

on:
  schedule:
    - cron: "22 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

env:
  USERAGENT: https://github.com/LuisErhardt/gibt-es-heute-pommes
  TZ: Europe/Berlin

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run fries availability script
        run: npm run start

      - name: Commit and push changes
        run: |
          git config user.name "Luis Erhardt"
          git config user.email "LuisErhardt@users.noreply.github.com"
          git add -A
          git commit -m "data" || echo "No changes to commit"
          git push
